import React from 'react'

export const metadata = {
    title: "Inside profile",
    description:"Generated by Next.js"
}

const layout = ({children}) => {
  return (
    <div>
        <h1>Profile layout</h1>
        {children}
    </div>
  )
}

export default layout